name: Continuous DeploymentAdd commentMore actions

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build & push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker rmi ${{ secrets.DOCKER_USERNAME }}/ai-server:latest || true
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ai-server:latest